apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofileq-deployment
  namespace: qagi
  labels:
    app: userprofileq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofileq
  template:
    metadata:
      labels:
        app: userprofileq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: userprofileq
        image: harbor.qagi.io/qagi/userprofileq:latest # Placeholder
        ports:
        - containerPort: 8000
        env:
        - name: CASSANDRA_HOSTS
          value: "cassandra.database.svc.cluster.local"
        - name: CASSANDRA_KEYSPACE
          value: "userprofilesq"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observability.svc.cluster.local:4317"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      imagePullSecrets:
      - name: harbor-registry-secret 