# kubernetes/base/vectorstore-q/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vectorstore-q
spec:
  selector:
    app: vectorstore-q
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  - name: metrics
    protocol: TCP
    port: 9091
    targetPort: 9091 