# .github/workflows/kustomize-edit.yml
name: Reusable - Update Kustomize Image Tag

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      new_image_tag:
        required: true
        type: string
    secrets:
      GIT_USER_NAME:
        required: true
      GIT_USER_EMAIL:
        required: true
      GIT_ACCESS_TOKEN:
        required: true

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Update image tag with Kustomize
        run: |
          cd kubernetes/base
          kustomize edit set image your-registry/${{ inputs.service_name }}:${{ inputs.new_image_tag }}
          
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "ci: Update image for ${{ inputs.service_name }} to ${{ inputs.new_image_tag }}" || echo "No changes to commit"
          git push 