replicas: 3
esJavaOpts: "-Xms1g -Xmx1g"
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi

# Enable settings for vector search capabilities
# The 'dense_vector' type is available in the default distribution,
# but being explicit about settings is good practice.
# No specific plugins are required for basic dense_vector support.
cluster:
  name: elasticsearch
  env:
    # Set any necessary environment variables for the cluster
    # For example, discovery settings if needed.
    # discovery.type: "single-node" # For local development 