# Grafana Helm chart values
# See: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

# Administrator credentials
# IMPORTANT: For production, use a more secure password or a secret.
adminPassword: "Password123"

# Expose Grafana via a LoadBalancer
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

# Configure the Prometheus instance as a pre-defined datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      # The URL points to the Prometheus server service within the same k8s cluster
      url: http://prometheus-server.q-platform.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Elasticsearch
      type: elasticsearch
      url: http://elasticsearch.database.svc.cluster.local:9200
      access: proxy
      jsonData:
        timeField: "@timestamp"
        logLevelField: "log_level"
        logMessageField: "message"
      
persistence:
  enabled: true
  size: 10Gi

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    workflow-dashboard:
      file: infra/grafana/dashboards/workflow_dashboard.json
    python-service-dashboard:
      file: infra/grafana/dashboards/python_service_dashboard.json
    logging-dashboard:
      file: infra/grafana/dashboards/logging_dashboard.json
    anomaly-dashboard:
      file: infra/grafana/dashboards/anomaly_dashboard.json 