# This configuration simulates a multi-datacenter setup for high availability.
# In a real multi-region deployment, you would have two separate Pulsar Helm releases,
# one for each region, and configure them to connect to each other.
# This file demonstrates the settings required for one of those clusters (e.g., the primary).

# --- Cluster Metadata ---
# This identifies the primary cluster and the secondary cluster for replication.
cluster:
  name: "pulsar-dc1"
  # This tells dc1 about dc2
  replication_clusters:
    - name: "pulsar-dc2"
      service_url: "pulsar://pulsar-dc2-proxy.q-platform-production.svc.cluster.local:6650"

# --- Component Configuration ---
broker:
  replicaCount: 2
  config:
    isAllowAutoUpdateSchema: "false"
    isSchemaValidationEnforced: "true"
    # Enable replication and set cluster names
    replicationTlsEnabled: false # Assuming inter-cluster traffic is on a private network
    clusterName: "pulsar-dc1"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

zookeeper:
  replicaCount: 3

bookkeeper:
  replicaCount: 3

proxy:
  replicaCount: 2 