apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: log-ingestion
  namespace: qagi
spec:
  image: harbor.qagi.io/qagi/aiops-log-ingestion:latest # Placeholder
  flinkVersion: v1_15
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/job.py
    parallelism: 2
    upgradeMode: stateless 