service_name: managerQ
version: "0.1.0"
api:
  host: "0.0.0.0"
  port: 8001
pulsar:
  service_url: "pulsar://localhost:6650"
  topics:
    platform_events: "persistent://public/default/platform-events"
vectorstore_q:
  url: "http://localhost:8020"
knowledgegraph_q:
  url: "http://localhost:8030"
quantumpulse:
  url: "http://localhost:8010"
