apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentq-reflector
spec:
  replicas: 1 # We only need one of this specialized agent
  selector:
    matchLabels:
      app: agentq-reflector
  template:
    metadata:
      labels:
        app: agentq-reflector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: agentq
        image: your-repo/agentq:latest # Replace with your image repository
        env:
        - name: AGENT_PERSONALITY
          value: "reflector"
        - name: LOGS_TO_PULSAR
          value: "true"
        # Add other environment variables for secrets, Ignite, etc. 