apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# Patches for the staging environment will go here.
# For example:
# patchesStrategicMerge:
#   - |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: manager-q
#     spec:
#       replicas: 1 